### PR TITLE
Release 1.8.1: https://github.com/JuliaLang/julia/releases/tag/v1.8.1

### PR DESCRIPTION
**Pull request by 13r0ck**
Please make sure the Julia REPL opens from both applications library, and CLI (using the `julia` command) on both ARM and x86.

### CODE REVIEW

**Comment by gangwerz** [comment]
I have confirmed `1+1` does equal 2, and `2+2` equals 4 in Julia on Pop 22.04 on the DevOne. I'm working on installing Pop on my Pi4 to test ARM.

I see builds for AMD64 on Pop 20.04, will this version be released there as well?

**Comment by gangwerz** [comment]
Testing on ARM is held up for me due to: https://github.com/pop-os/raspi-img/issues/16

I will continue testing as soon as I can.

**Comment by 13r0ck** [comment]
@gangwerz can you download the deb and install it on some other linux arm distro?

**Review by gangwerz — APPROVED** [review]
Looks good!

**Review by mmstick — APPROVED** [review]

**Pull request merged**
